### ISSUE TITLE
Version 3.0.3 does not support PHP 7.0

### ISSUE THREAD

**Issue by ghost** [marketing-factory/amazon_affiliate#2]
No Products/Books are shown.

**Comment by garbast** [comment]
Could you elaborate this more? PHP Error Log anything? Just does not support is not enough to handle this in a reasonable time.

**Comment by ghost** [comment]
There is no PHP Error thrown out. So I searched a long time until I found out that the problem was to change from PHP 5.6 to 7.0. 
The problem is only in FE. In BE everything works fine. It seems as if the markers won't be filled.

<img width="777" alt="bildschirmfoto php5_6" src="https://cloud.githubusercontent.com/assets/16305058/17168684/07301f2a-53e4-11e6-95b9-75bb7593f04c.png">
<img width="767" alt="bildschirmfoto php7_0" src="https://cloud.githubusercontent.com/assets/16305058/17168689/0d647062-53e4-11e6-94bf-82373a598237.png">

**Comment by ghost** [comment]
OK. Back again. 

Hi @garbast , @sfsmfc 
I found a hint, but I cannot see the error. 
First I have to say, that not only with php7 there are problems but sometimes with php5.6 too.

I debugged with 

``` php
\TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump($product);
```

The result is, that only books (and products) that are cached in 'amazonEcs.productCache' are rendered. 
You can have a look at the page with the debugging-Information [here](https://www.evernote.com/l/AK_f1ftNr4dJE4eAlpDbCwukx1OdRxLEofM)
https://www.evernote.com/l/AK_f1ftNr4dJE4eAlpDbCwukx1OdRxLEofM

This test was made under:
php5.6
TYPO3 7.6.9
EXT:amazon_affiliate 3.0.4 (commit fd9d2bd)
EXT:amazon_affiliate is "stand alone" and a plugin in a content-element in tx_news 5.1.0

The same test under php7.0 has as result, that 'amazonEcs.productCache' is empty and therefore no books and no products are rendered. --> take a look at this screenshots.
<img width="904" alt="bildschirmfoto 2016-10-05 um 23 30 19" src="https://cloud.githubusercontent.com/assets/16305058/19132477/eb102b9e-8b53-11e6-988c-8b20e66f85bb.png">
<img width="851" alt="bildschirmfoto 2016-10-05 um 23 39 33" src="https://cloud.githubusercontent.com/assets/16305058/19132674/048b846e-8b55-11e6-863d-6300423d28db.png">

So I hope this Information may help.

**Comment by ghost** [comment]
Hi Sebastian, 

did my latest comment help you in any way?

**Comment by garbast** [comment]
No that is no hint in the slightest. By this informations im not able to help you.
